### ISSUE TITLE
不支持v8.6.2.0，请问能支持下吗？

### ISSUE THREAD

**Issue by a2dict** [deadash/pbb_crack#10]
你好，软件不支持v8.6.2.0版本PBB，请问能支持下吗？谢谢。

**Comment by deadash** [comment]
https://www.pyc.com.cn/Application/AppVersion.aspx?pid=18
下载最新版本 8.7.3

偏移地址(视频+图片等)：
PycPlayer.exe+1101CB8
PycPlus.dll+152C0

**Comment by deadash** [comment]
https://github.com/deadash/pbb_crack/releases

**Comment by BlademasterQAQ** [comment]
> https://www.pyc.com.cn/Application/AppVersion.aspx?pid=18 下载最新版本 8.7.3
> 
> 偏移地址(视频+图片等)： PycPlayer.exe+1101CB8 PycPlus.dll+152C0

您好，请问现在这个项目还能正常使用吗？
我不太清楚加密端使用的pbb版本，播放端使用的是 8.7.3 版本。
尝试使用`dumpkey.exe`会得到`02fe03fe04fe05fe06fe07fe08fe09fe`这样的错误密码，解密失败。
使用x64dbg在“内存布局”中PycPlayer.exe的基址上偏移1101CB8，使用得到的十六进制码同样解密失败。
是我的操作不对还是本项目无法使用了呢？

还想问下现在群45565573是已经关闭了？申请加群了很多天都没有通过。

谢谢！
