### ISSUE TITLE
文件key找出来了，但是cpu和gpu都计算失败？

### ISSUE THREAD

**Issue by UESTC-LXY** [deadash/pbb_crack#2]
是电脑原因嘛

**Comment by UESTC-LXY** [comment]
用的示例Demo

**Comment by DuoBright** [comment]
您好，请问这个是怎样用的？下载后没找到运行文件  @UESTC-LXY

**Comment by letme2** [comment]
完全不懂编程，请问这个文件下载下来之后要怎么使用？

**Comment by letme2** [comment]
> 您好，请问这个是怎样用的？下载后没找到运行文件 @UESTC-LXY

完全不懂编程，请问这个文件下载下来之后要怎么使用？

**Comment by deadash** [comment]
> 您好，请问这个是怎样用的？下载后没找到运行文件 @UESTC-LXY

请点击release即可下载。
