### ISSUE TITLE
请问一下作者，某些视频报这个错，有办法解决么？

### ISSUE THREAD

**Issue by handsomeliangliang** [deadash/pbb_crack#3]
运行完成.
 错误:计算失败,请选择 CPU计算
 文件key:3136406164656768696A6E6F6F757579
 开始运行...

**Comment by deadash** [comment]
对于2017.4以前的视频可以计算，之后的视频只能提取key来解密

**Comment by bo8888** [comment]
解密的视频无法播放啊

**Comment by letme2** [comment]
完全不懂编程，请问这个文件下载下来之后要怎么使用？

**Comment by letme2** [comment]
> 解密的视频无法播放啊

完全不懂编程，请问这个文件下载下来之后要怎么使用？

**Comment by deadash** [comment]
> 解密的视频无法播放啊

无法播放代表密钥失败，目前没有正确key解密失败的例子。
