### ISSUE TITLE
这个应该如何使用？

### ISSUE THREAD

**Issue by tangxuesong6** [deadash/pbb_crack#4]
如何提取出视频？

**Comment by deadash** [comment]
打开原播放器播放，使用get_pwd提取视频密钥，关闭播放器播放，使用pbb_crack提取

**Comment by wxlcola804** [comment]
get_pwd从哪里获取

**Comment by letme2** [comment]
完全不懂编程，请问这个文件下载下来之后要怎么使用？

**Comment by deadash** [comment]
https://github.com/deadash/pbb_crack/releases
