### ISSUE TITLE
mac有密怎么提取呢

### ISSUE THREAD

**Issue by andywong2019** [deadash/pbb_crack#6]
mac系统有密怎么提取呢

**Comment by letme2** [comment]
完全不懂编程，请问这个文件下载下来之后要怎么使用？

**Comment by deadash** [comment]
> mac系统有密怎么提取呢

目前不知道mac系统，建议你到win下提取后在mac下使用，如果你有好的建议欢迎提交PR

**Comment by Cope9560** [comment]
qq群是多少，之前那个搜索不到了，另外 excel文件不能提取吗？
