### ISSUE TITLE
像某个单位出事了互相推责任

### ISSUE THREAD

**Issue by houko** [deadash/pbb_crack#7]
![image](https://user-images.githubusercontent.com/12625278/46779249-7ee45500-cd49-11e8-8331-82478a7b71fa.png)

GPU: 你让那CPU那货去搞啊
CPU: 不是给你说了这事归GUP管

**Comment by JasonHuang** [comment]
一样的，不知道是不是作者没有再维护这个项目了？

**Comment by letme2** [comment]
完全不懂编程，请问这个文件下载下来之后要怎么使用？

**Comment by letme2** [comment]
> 一样的，不知道是不是作者没有再维护这个项目了？

完全不懂编程，请问这个文件下载下来之后要怎么使用？

**Comment by deadash** [comment]
> 一样的，不知道是不是作者没有再维护这个项目了？

这个项目一直可以使用,目前官方并没有修改算法, 所以并不需要更新

**Comment by deadash** [comment]
> > 一样的，不知道是不是作者没有再维护这个项目了？
> 
> 完全不懂编程，请问这个文件下载下来之后要怎么使用？

我会更新wiki，如有疑问，请加入QQ群。

**Comment by deadash** [comment]
> ![image](https://user-images.githubusercontent.com/12625278/46779249-7ee45500-cd49-11e8-8331-82478a7b71fa.png)
> 
> GPU: 你让那CPU那货去搞啊
> CPU: 不是给你说了这事归GUP管

之前版本存在漏洞可以无密破解(CPU\GPU只是方式不同，针对有的电脑不支持gpu的情况)，目前主要支持有密提取。
